# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/richcal',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/richcal',
                'lib_path': 'richcal'},
  'syms': { 'richcal.heatmap': {},
            'richcal.layout': { 'richcal.layout.grid_bounds': ('layout.html#grid_bounds', 'richcal/layout.py'),
                                'richcal.layout.saturday_on_or_after': ('layout.html#saturday_on_or_after', 'richcal/layout.py'),
                                'richcal.layout.sunday_on_or_before': ('layout.html#sunday_on_or_before', 'richcal/layout.py'),
                                'richcal.layout.week_col': ('layout.html#week_col', 'richcal/layout.py'),
                                'richcal.layout.weekday_row': ('layout.html#weekday_row', 'richcal/layout.py')},
            'richcal.levels': { 'richcal.levels.quantile_thresholds': ('levels.html#quantile_thresholds', 'richcal/levels.py'),
                                'richcal.levels.to_level': ('levels.html#to_level', 'richcal/levels.py')}}}
