# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/richcal',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/richcal',
                'lib_path': 'richcal'},
  'syms': {'richcal.heatmap': {}, 'richcal.layout': {}, 'richcal.levels': {}}}
