"""Fill in a module description here

Docs: https://doyu.github.io/richcalcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #f05b8dd6
def foo(): pass
