"""`CalendarHeatmap`: a Rich renderable GitHub-style annual heatmap.

Docs: https://doyu.github.io/richcalheatmap.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_heatmap.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/02_heatmap.ipynb #e1f2a3b4
import math
from datetime import date, timedelta
from collections.abc import Mapping, Sequence
from rich.text import Text
from .levels import quantile_thresholds, to_level
from .layout import grid_bounds, year_blocks, month_label_cols
