"""`CalendarHeatmap`: a Rich renderable GitHub-style annual heatmap.

Docs: https://doyu.github.io/richcalheatmap.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_heatmap.ipynb.

# %% auto #0
__all__ = ['default_palette', 'CalendarHeatmap']

# %% ../nbs/02_heatmap.ipynb #e1f2a3b4
import math
from datetime import date, timedelta
from collections.abc import Mapping, Sequence
from rich.text import Text
from .levels import quantile_thresholds, to_level
from .layout import grid_bounds, year_blocks, month_label_cols

# %% ../nbs/02_heatmap.ipynb #b2c3d4e5
_EMPTY = "grey23"
_GREEN_RAMP = ["#0e4429", "#006d32", "#26a641", "#39d353"]  # 4 activity shades

def default_palette(level_max):
    "Built-in GitHub-green palette of length level_max+1 (level 0 = empty)."
    if not 1 <= level_max <= len(_GREEN_RAMP):
        raise ValueError(f"no built-in palette for level_max={level_max}; pass palette=")
    return [_EMPTY] + _GREEN_RAMP[len(_GREEN_RAMP) - level_max:]

class CalendarHeatmap:
    "Rich renderable: GitHub-style annual activity heatmap from {date: value}."
    def __init__(self, data, start, end, level_max=4, thresholds=None,
                 palette=None, as_of=None, show_months=True,
                 show_weekdays=True, show_legend=True):
        if start > end: raise ValueError("start must be <= end")
        if level_max < 1: raise ValueError("level_max must be >= 1")
        if thresholds is not None:
            thresholds = list(thresholds)
            if len(thresholds) != level_max - 1:
                raise ValueError(f"thresholds length must be {level_max - 1}")
            if any(thresholds[i] > thresholds[i + 1] for i in range(len(thresholds) - 1)):
                raise ValueError("thresholds must be non-decreasing")
        observed = self._observed_values(data, start, end, as_of)
        for v in observed:
            if not math.isfinite(v) or v < 0:
                raise ValueError(f"observed values must be finite and >= 0; got {v!r}")
        self.data, self.start, self.end = data, start, end
        self.level_max, self.as_of = level_max, as_of
        self.show_months, self.show_weekdays, self.show_legend = show_months, show_weekdays, show_legend
        self.thresholds = thresholds if thresholds is not None else quantile_thresholds(observed, level_max)
        self.palette = list(palette) if palette is not None else default_palette(level_max)
        self.blocks = year_blocks(start, end)

    @staticmethod
    def _observed_values(data, start, end, as_of):
        "Values of in-window, non-future days that are present in data."
        out, d = [], start
        while d <= end:
            if (as_of is None or d <= as_of) and d in data:
                out.append(data[d])
            d += timedelta(days=1)
        return out

# %% ../nbs/02_heatmap.ipynb #06ef8dc0
_WEEKDAYS = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"]

def _month_header(self, block_start, block_end, grid_start, n_cols, left_pad):
    row = [" "] * (n_cols * 2)
    for col, label in month_label_cols(block_start, block_end, grid_start):
        for i, ch in enumerate(label):
            if 0 <= col * 2 + i < len(row):
                row[col * 2 + i] = ch
    return Text(" " * left_pad + "".join(row))

def _render_block(self, year, block_start, block_end, multi):
    grid_start, n_cols = grid_bounds(block_start, block_end)
    left_pad = 3 if self.show_weekdays else 0
    lines = []
    if multi:
        lines.append(Text(str(year), style="bold"))
    if self.show_months:
        lines.append(self._month_header(block_start, block_end, grid_start, n_cols, left_pad))
    for r in range(7):
        line = Text()
        if self.show_weekdays:
            line.append(_WEEKDAYS[r] + " ")
        for col in range(n_cols):
            d = grid_start + timedelta(days=col * 7 + r)
            if d < block_start or d > block_end:
                line.append("  ")
            elif self.as_of is not None and d > self.as_of:
                line.append("· ", style="grey37")
            else:
                line.append("■ ", style=self.palette[to_level(self.data.get(d, 0), self.thresholds)])
        lines.append(line)
    return lines

def _legend(self):
    leg = Text("Less ")
    for lvl in range(self.level_max + 1):
        leg.append("■ ", style=self.palette[lvl])
    leg.append("More")
    return leg

def __rich_console__(self, console, options):
    multi = len(self.blocks) > 1
    for year, bs, be in self.blocks:
        yield from self._render_block(year, bs, be, multi)
        yield Text("")
    if self.show_legend:
        yield self._legend()

CalendarHeatmap._month_header = _month_header
CalendarHeatmap._render_block = _render_block
CalendarHeatmap._legend = _legend
CalendarHeatmap.__rich_console__ = __rich_console__
