"""Map dates onto a Sunday-first weekday × week grid.

Docs: https://doyu.github.io/richcallayout.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_layout.ipynb.

# %% auto #0
__all__ = ['weekday_row', 'sunday_on_or_before', 'saturday_on_or_after', 'week_col', 'grid_bounds']

# %% ../nbs/01_layout.ipynb #a7b8c9d0
import calendar
from datetime import date, timedelta

# %% ../nbs/01_layout.ipynb #e036fca9
def weekday_row(d):
    "Row index with Sunday=0 .. Saturday=6."
    return (d.weekday() + 1) % 7

def sunday_on_or_before(d):
    "The Sunday on or before `d`."
    return d - timedelta(days=weekday_row(d))

def saturday_on_or_after(d):
    "The Saturday on or after `d`."
    return d + timedelta(days=(5 - d.weekday()) % 7)

def week_col(d, grid_start):
    "Column index of `d` measured in weeks from `grid_start` (a Sunday)."
    return (d - grid_start).days // 7

def grid_bounds(block_start, block_end):
    "Return (grid_start, n_cols) of full Sunday-first weeks covering [block_start, block_end]."
    gs = sunday_on_or_before(block_start)
    ge = saturday_on_or_after(block_end)
    return gs, (ge - gs).days // 7 + 1
