"""Map dates onto a Sunday-first weekday × week grid.

Docs: https://doyu.github.io/richcallayout.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_layout.ipynb.

# %% auto #0
__all__ = ['weekday_row', 'sunday_on_or_before', 'saturday_on_or_after', 'week_col', 'grid_bounds', 'year_blocks',
           'month_label_cols']

# %% ../nbs/01_layout.ipynb #a7b8c9d0
import calendar
from datetime import date, timedelta

# %% ../nbs/01_layout.ipynb #e036fca9
def weekday_row(d):
    "Row index with Sunday=0 .. Saturday=6."
    return (d.weekday() + 1) % 7

def sunday_on_or_before(d):
    "The Sunday on or before `d`."
    return d - timedelta(days=weekday_row(d))

def saturday_on_or_after(d):
    "The Saturday on or after `d`."
    return d + timedelta(days=(5 - d.weekday()) % 7)

def week_col(d, grid_start):
    "Column index of `d` measured in weeks from `grid_start` (a Sunday)."
    return (d - grid_start).days // 7

def grid_bounds(block_start, block_end):
    "Return (grid_start, n_cols) of full Sunday-first weeks covering [block_start, block_end]."
    gs = sunday_on_or_before(block_start)
    ge = saturday_on_or_after(block_end)
    return gs, (ge - gs).days // 7 + 1

# %% ../nbs/01_layout.ipynb #defe463c
def year_blocks(start, end):
    "Split [start, end] into (year, block_start, block_end); one block per calendar year."
    if start > end: raise ValueError("start must be <= end")
    if start.year == end.year: return [(start.year, start, end)]
    out = []
    for y in range(start.year, end.year + 1):
        out.append((y, max(start, date(y, 1, 1)), min(end, date(y, 12, 31))))
    return out

def month_label_cols(block_start, block_end, grid_start):
    "List of (week_col, 'Mon') for the first day of each month in [block_start, block_end]."
    out, seen, d = [], set(), block_start
    while d <= block_end:
        if (d.year, d.month) not in seen:
            seen.add((d.year, d.month))
            out.append((week_col(d, grid_start), calendar.month_abbr[d.month]))
        d += timedelta(days=1)
    return out
