"""Map dates onto a Sunday-first weekday × week grid.

Docs: https://doyu.github.io/richcallayout.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_layout.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/01_layout.ipynb #a7b8c9d0
import calendar
from datetime import date, timedelta
