"""Map raw daily values to integer activity levels.

Docs: https://doyu.github.io/richcallevels.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_levels.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/00_levels.ipynb #c3d4e5f6
import statistics
from bisect import bisect_right
