"""Map raw daily values to integer activity levels.

Docs: https://doyu.github.io/richcallevels.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_levels.ipynb.

# %% auto #0
__all__ = ['to_level', 'quantile_thresholds']

# %% ../nbs/00_levels.ipynb #c3d4e5f6
import statistics
from bisect import bisect_right

# %% ../nbs/00_levels.ipynb #f6a7b8c9
def to_level(value, thresholds):
    "Integer activity level 0..len(thresholds)+1; 0 when value<=0."
    if value <= 0: return 0
    return 1 + bisect_right(thresholds, value)

def quantile_thresholds(values, level_max):
    "Ascending cut points (len level_max-1) splitting positive `values` into `level_max` groups."
    pos = sorted(v for v in values if v > 0)
    if level_max <= 1 or len(pos) < 2: return []
    return statistics.quantiles(pos, n=level_max, method="inclusive")
